#include <ec.h>
#include <endomorphism_action.h>
#include <hd.h>
#include <id2iso.h>
#include <inttypes.h>
#include <locale.h>
#include <mem.h>
#include <quaternion.h>
#include <stdint.h>

static void
id2iso_wipe_digits(digit_t *digits, size_t count)
{
    volatile digit_t *p = (volatile digit_t *)digits;
    while (count-- != 0u)
        *p++ = 0;
}
#include <stdlib.h>
#include <tools.h>
#include <torsion_constants.h>


static int
_fixed_degree_isogeny_impl(quat_left_ideal_t *lideal,
                           const ibz_t *u,
                           bool small,
                           theta_couple_curve_t *E34,
                           theta_couple_point_t *P12,
                           size_t numP,
                           const int index_alternate_order)
{

    if (lideal == NULL || u == NULL || E34 == NULL ||
        (numP != 0 && P12 == NULL) ||
        index_alternate_order < 0 ||
        index_alternate_order > NUM_ALTERNATE_EXTREMAL_ORDERS ||
        ibz_cmp(u, &ibz_const_zero) <= 0 || ibz_is_even(u))
        return ID2ISO_STATUS_FATAL;

    // var declaration
    int ret;
    ibz_t two_pow, tmp;
    quat_alg_elem_t theta;

    ec_curve_t E0;
    copy_curve(&E0, &CURVES_WITH_ENDOMORPHISMS[index_alternate_order].curve);
    ec_curve_normalize_A24(&E0);

    unsigned length;

    int u_bitsize = ibz_bitsize(u);

    // deciding the power of 2 of the dim2 isogeny we use for this
    // the smaller the faster, but if it set too low there is a risk that
    // RepresentInteger will fail
    if (!small) {
        // in that case, we just set it to be the biggest value possible
        length = TORSION_EVEN_POWER - HD_extra_torsion;
    } else {
        int candidate_length = ibz_bitsize(&QUATALG_PINFTY.p) +
                               QUAT_repres_bound_input - u_bitsize;
        if (candidate_length <= 0 || u_bitsize >= candidate_length ||
            candidate_length >= TORSION_EVEN_POWER - HD_extra_torsion)
            return ID2ISO_STATUS_FATAL;
        length = (unsigned)candidate_length;
    }
    if (length == 0)
        return ID2ISO_STATUS_FATAL;

    // var init
    ibz_init(&two_pow);
    ibz_init(&tmp);
    quat_alg_elem_init(&theta);

    ibz_pow(&two_pow, &ibz_const_two, length);
    ibz_copy(&tmp, u);
    if (ibz_cmp(&two_pow, &tmp) <= 0 || ibz_is_even(&tmp)) {
        ret = ID2ISO_STATUS_FATAL;
        goto cleanup;
    }

    // computing the endomorphism theta of norm u * (2^(length) - u)
    ibz_sub(&tmp, &two_pow, &tmp);
    ibz_mul(&tmp, &tmp, u);
    if (ibz_is_even(&tmp)) {
        ret = ID2ISO_STATUS_FATAL;
        goto cleanup;
    }

    // setting-up the quat_represent_integer_params
    quat_represent_integer_params_t ri_params;
    ri_params.primality_test_iterations = QUAT_represent_integer_params.primality_test_iterations;

    ri_params.order = &EXTREMAL_ORDERS[index_alternate_order];
    ri_params.algebra = &QUATALG_PINFTY;

#ifndef NDEBUG
    assert(quat_lattice_contains(NULL, &ri_params.order->order, &ri_params.order->z));
    assert(quat_lattice_contains(NULL, &ri_params.order->order, &ri_params.order->t));
#endif

    ret = quat_represent_integer(&theta, &tmp, 1, &ri_params);

    if (!ret) {
        goto cleanup;
    }
    /* paper Issue 9: theta represents u*(2^length-u), while the ideal
     * generated by theta and u has reduced norm u by construction. */
    if (!quat_lideal_create_with_norm(
            lideal,
            &theta,
            u,
            &EXTREMAL_ORDERS[index_alternate_order].order,
            &QUATALG_PINFTY)) {
        ret = ID2ISO_STATUS_FATAL;
        goto cleanup;
    }
    /* The local order is an HNF copy of this static precomputation.  Repair
     * the persistent parent pointer immediately, including later failures. */
    lideal->parent_order = &EXTREMAL_ORDERS[index_alternate_order].order;

#ifndef NDEBUG
    ibz_t test_norm, test_denom;
    ibz_init(&test_denom);
    ibz_init(&test_norm);
    assert(quat_alg_norm(&test_norm, &test_denom, &theta, &QUATALG_PINFTY));
    assert(ibz_is_one(&test_denom));
    assert(ibz_cmp(&test_norm, &tmp) == 0);
    assert(!ibz_is_even(&tmp));
    assert(quat_lattice_contains(NULL, &EXTREMAL_ORDERS[index_alternate_order].order, &theta));
    ibz_finalize(&test_norm);
    ibz_finalize(&test_denom);
#endif

    ec_basis_t B0_two;
    // copying the basis
    copy_basis(&B0_two, &CURVES_WITH_ENDOMORPHISMS[index_alternate_order].basis_even);
    assert(test_basis_order_twof(&B0_two, &E0, TORSION_EVEN_POWER));
    ec_dbl_iter_basis(&B0_two, TORSION_EVEN_POWER - length - HD_extra_torsion, &B0_two, &E0);

    assert(test_basis_order_twof(&B0_two, &E0, length + HD_extra_torsion));

    // now we set-up the kernel
    theta_couple_point_t T1;
    theta_couple_point_t T2, T1m2;

    copy_point(&T1.P1, &B0_two.P);
    copy_point(&T2.P1, &B0_two.Q);
    copy_point(&T1m2.P1, &B0_two.PmQ);

    // multiplication of theta by (u)^-1 mod 2^(length+2)
    ibz_mul(&two_pow, &two_pow, &ibz_const_two);
    ibz_mul(&two_pow, &two_pow, &ibz_const_two);
    ibz_copy(&tmp, u);
    if (!ibz_invmod(&tmp, &tmp, &two_pow) || ibz_is_even(&tmp)) {
        ret = ID2ISO_STATUS_FATAL;
        goto cleanup;
    }

    ibz_mul(&theta.coord[0], &theta.coord[0], &tmp);
    ibz_mul(&theta.coord[1], &theta.coord[1], &tmp);
    ibz_mul(&theta.coord[2], &theta.coord[2], &tmp);
    ibz_mul(&theta.coord[3], &theta.coord[3], &tmp);

    // applying theta to the basis
    ec_basis_t B0_two_theta;
    copy_basis(&B0_two_theta, &B0_two);
    if (!endomorphism_application_even_basis(
            &B0_two_theta,
            index_alternate_order,
            &E0,
            &theta,
            length + HD_extra_torsion)) {
        ret = ID2ISO_STATUS_FATAL;
        goto cleanup;
    }

    // Ensure the basis we're using has the expected order
    if (!test_basis_order_twof(&B0_two_theta, &E0, length + HD_extra_torsion)) {
        ret = ID2ISO_STATUS_FATAL;
        goto cleanup;
    }

    // Set-up the domain E0 x E0
    theta_couple_curve_t E00;
    E00.E1 = E0;
    E00.E2 = E0;

    // Set-up the kernel from the bases
    theta_kernel_couple_points_t dim_two_ker;
    copy_bases_to_kernel(&dim_two_ker, &B0_two, &B0_two_theta);

    ret = theta_chain_compute_and_eval(length, &E00, &dim_two_ker, true, E34, P12, numP);
    if (!ret)
        goto cleanup;

    ret = (int)length;

cleanup:
    // var finalize
    ibz_finalize(&two_pow);
    ibz_finalize(&tmp);
    quat_alg_elem_finalize(&theta);

    return ret;
}

int
fixed_degree_isogeny_and_eval(quat_left_ideal_t *lideal,
                              const ibz_t *u,
                              bool small,
                              theta_couple_curve_t *E34,
                              theta_couple_point_t *P12,
                              size_t numP,
                              const int index_alternate_order)
{
    return _fixed_degree_isogeny_impl(lideal, u, small, E34, P12, numP, index_alternate_order);
}

#if defined(TARGET_ARM)
#undef ID2ISO_DEBUG_PRINT
#define ID2ISO_DEBUG_PRINT 0
#elif !defined(ID2ISO_DEBUG_PRINT)
#define ID2ISO_DEBUG_PRINT 0
#endif

static int
weil_basis(fp2_t *out, int e, const ec_basis_t *basis, const ec_curve_t *curve)
{
    if (out == NULL || basis == NULL || curve == NULL || e <= 0)
        return 0;

    ibz_vec_2_t tmp;
    ec_point_t wi;
    ec_curve_t ec;
    ec_point_init(&wi);
    ec_curve_init(&ec);
    ibz_vec_2_init(&tmp);
    ibz_set(&(tmp[0]), 1);
    ibz_set(&(tmp[1]), 1);
    int status = ec_biscalar_mul_ibz_vec(&wi, &tmp, e, basis, curve);
    if (status) {
        copy_curve(&ec, curve);
        weil(out, e, &basis->P, &basis->Q, &wi, &ec);
    }
    ibz_vec_2_finalize(&tmp);
    return status;
}

static int
ec_basis_scalar_mul_ibz(ec_basis_t *out, int e, const ibz_t *n, const ec_basis_t *input, const ec_curve_t *curve)
{
    if (out == NULL || n == NULL || input == NULL || curve == NULL ||
        e <= 0 || e >= IBZ_BITS - 1)
        return 0;

    int status = 0;
    ec_basis_t candidate;
#ifndef NDEBUG
    fp2_t prod, r1, r2;
    digit_t array[NWORDS_ORDER];
    if (!weil_basis(&r1, e, input, curve))
        return 0;
#endif
    ibz_vec_2_t tmp;
    ec_basis_t used;
    copy_basis(&used, input);
    ibz_vec_2_init(&tmp);
    ibz_copy(&(tmp[0]), n);
    ibz_set(&(tmp[1]), 0);
    if (!ec_biscalar_mul_ibz_vec(&candidate.P, &tmp, e, &used, curve))
        goto cleanup;
    ibz_swap((&tmp[0]), &(tmp[1]));
    if (!ec_biscalar_mul_ibz_vec(&candidate.Q, &tmp, e, &used, curve))
        goto cleanup;
    ibz_copy(&(tmp[0]), &(tmp[1]));
    ibz_t power_two;
    ibz_init(&power_two);
    ibz_pow(&power_two, &ibz_const_two, e);
    ibz_sub(&(tmp[1]), &power_two, &(tmp[0]));
    ibz_finalize(&power_two);
    if (!ec_biscalar_mul_ibz_vec(&candidate.PmQ, &tmp, e, &used, curve))
        goto cleanup;
#ifndef NDEBUG
    if (ibz_is_odd(n)) {
        assert(test_basis_order_twof(&candidate, curve, e));
        assert(weil_basis(&r2, e, &candidate, curve));
        if (ibz_bitsize(n) < (int)(sizeof(digit_t) * 8 * NWORDS_ORDER)) {
#if (ID2ISO_DEBUG_PRINT > 1)
            debug_print("pairing test for scalar mul runs");
#endif
            memset(array, 0, NWORDS_ORDER * sizeof(digit_t));
            if (!ibz_to_mp_digits_checked(array, NWORDS_ORDER, n)) {
                id2iso_wipe_digits(array, NWORDS_ORDER);
                goto cleanup;
            }
            fp2_pow_vartime(&prod, &r1, &array[0], NWORDS_ORDER);
            fp2_pow_vartime(&prod, &prod, &array[0], NWORDS_ORDER);
            id2iso_wipe_digits(array, NWORDS_ORDER);
#if (ID2ISO_DEBUG_PRINT > 2)
            fp2_print("       r2 ", &r2);
            fp2_print("     prod ", &prod);
            fp_neg(&r1.im, &prod.im);
            fp_copy(&r1.re, &prod.re);
            fp2_print("conj prod ", &r1);
#endif
            assert(fp2_is_equal(&prod, &r2));
        }
    }
#endif
    copy_basis(out, &candidate);
    status = 1;

cleanup:
    ibz_vec_2_finalize(&tmp);
    return status;
}

static int
dim2id2iso_ideal_to_isogeny_clapotis_core(quat_alg_elem_t *beta1,
                                          quat_alg_elem_t *beta2,
                                          ibz_t *u,
                                          ibz_t *v,
                                          ibz_t *d1,
                                          ibz_t *d2,
                                          ec_curve_t *codomain,
                                          ec_basis_t *basis,
                                          const quat_left_ideal_t *lideal,
                                          const quat_alg_t *Bpoo,
                                          bool publish_auxiliary_outputs)
{
    if ((publish_auxiliary_outputs &&
         (beta1 == NULL || beta2 == NULL || u == NULL || v == NULL ||
          d1 == NULL || d2 == NULL)) ||
        (!publish_auxiliary_outputs &&
         (beta1 != NULL || beta2 != NULL || u != NULL || v != NULL ||
          d1 != NULL || d2 != NULL)) ||
        codomain == NULL || basis == NULL ||
        lideal == NULL || Bpoo == NULL ||
        ibz_cmp(&lideal->norm, &ibz_const_zero) <= 0 ||
        ibz_is_zero(&lideal->lattice.denom))
        return ID2ISO_STATUS_FATAL;

    quat_alg_elem_t mu1, mu2, small, theta;
    ibz_t tmp;
    ec_basis_t E0_basis, B2;
    fp2_t r1, r2, prod;
    digit_t array[NWORDS_ORDER];
    struct theta_kernel_couple_points ker;
    theta_couple_curve_t E0E0;
    theta_couple_curve_t theta_codomain;
    if (publish_auxiliary_outputs) {
        ibz_copy(u, &ibz_const_one);
        ibz_copy(v, &ibz_const_one);
    }
    ibz_t n, d, two_c;
    /* The curve-only entry point does not publish d1, but the degree is live
     * throughout the isogeny construction.  Keeping just this one scalar in
     * the core replaces the wrapper's two quaternion elements and four
     * fixed-precision integers. */
    ibz_t internal_d1;
    ibz_t *degree1 = d1;
    if (!publish_auxiliary_outputs) {
        ibz_init(&internal_d1);
        degree1 = &internal_d1;
    }
#ifndef NDEBUG
    /* d2 is only needed after its validation by a debug invariant. */
    ibz_t internal_d2;
    ibz_t *degree2 = d2;
    if (!publish_auxiliary_outputs) {
        ibz_init(&internal_d2);
        degree2 = &internal_d2;
    }
#else
    /* In release curve-only builds tmp holds d2 until it has been checked. */
    ibz_t *degree2 = publish_auxiliary_outputs ? d2 : &tmp;
#endif
    ibz_init(&n);
    ibz_init(&d);
    ibz_init(&two_c);
    quat_alg_elem_init(&theta);
    quat_alg_elem_init(&mu1);
    quat_alg_elem_init(&mu2);
    quat_alg_elem_init(&small);
    ibz_init(&tmp);

    int ret = ID2ISO_STATUS_FATAL;
    int used_torsion = QUAT_qlapoti_used_power_of_two;
    int c;

    ret = quat_qlapoti(&mu1,
                       &mu2,
                       &theta,
                       &small,
                       lideal,
                       Bpoo,
                       QUAT_qlapoti_iteration_bound,
                       QUAT_qlapoti_gen_bound_bits,
                       used_torsion,
                       &QUAT_cornacchia_extended_params);

    if (ret == QUAT_QLAPOTI_FATAL) {
        ret = ID2ISO_STATUS_FATAL;
        goto cleanup;
    }
    if (ret == QUAT_QLAPOTI_RETRY) {
        ret = 0;
        goto cleanup;
    }
    if (ret != QUAT_QLAPOTI_SUCCESS &&
        ret != QUAT_QLAPOTI_SUCCESS_TRANSFORMED) {
        ret = ID2ISO_STATUS_FATAL;
        goto cleanup;
    }

    {
        int qlapoti_status = ret;
        quat_alg_normalize(&theta);
#if (ID2ISO_DEBUG_PRINT > 2)
        quat_alg_elem_print(&theta);
#endif
        used_torsion = used_torsion -
                        (qlapoti_status == QUAT_QLAPOTI_SUCCESS_TRANSFORMED);
        if (used_torsion <= 0 || used_torsion > TORSION_EVEN_POWER) {
            ret = ID2ISO_STATUS_FATAL;
            goto cleanup;
        }
        c = TORSION_EVEN_POWER - used_torsion;
        if (c < 0 || c >= IBZ_BITS - 1) {
            ret = ID2ISO_STATUS_FATAL;
            goto cleanup;
        }
        ibz_pow(&two_c, &ibz_const_two, c);

#if (ID2ISO_DEBUG_PRINT > 2)
        debug_print("used_torsion adjusted after Qlapoti");
#endif
        quat_alg_conj(&theta, &theta);
        {
            // norm d1
            if (!quat_alg_norm(degree1, &d, &mu1, Bpoo) || !ibz_is_one(&d)) {
                ret = ID2ISO_STATUS_FATAL;
                goto cleanup;
            }
            ibz_mul(degree1, degree1, &lideal->norm);
            if (!quat_alg_norm(&n, &d, &small, Bpoo) ||
                !ibz_is_one(&d) || ibz_is_zero(&n)) {
                ret = ID2ISO_STATUS_FATAL;
                goto cleanup;
            }
            ibz_div(degree1, &d, degree1, &n);
            if (!ibz_is_zero(&d)) {
                ret = ID2ISO_STATUS_FATAL;
                goto cleanup;
            }

            if (publish_auxiliary_outputs) {
                // beta1
                quat_alg_mul(beta1, &mu1, &small, Bpoo);
                if (!quat_alg_norm(&n, &d, &small, Bpoo) ||
                    ibz_is_zero(&lideal->norm)) {
                    ret = ID2ISO_STATUS_FATAL;
                    goto cleanup;
                }
                ibz_div(&n, &d, &n, &lideal->norm);
                if (!ibz_is_zero(&d)) {
                    ret = ID2ISO_STATUS_FATAL;
                    goto cleanup;
                }
                ibz_mul(&beta1->denom, &beta1->denom, &n);
                quat_alg_normalize(beta1);
            }

#ifndef NDEBUG
            if (publish_auxiliary_outputs) {
            quat_left_ideal_t I1;
            quat_left_ideal_t betatest;
            quat_alg_elem_t gen;
            quat_left_ideal_init(&I1);
            quat_left_ideal_init(&betatest);
            quat_alg_elem_init(&gen);
            assert(quat_lattice_contains(NULL, &lideal->lattice, &small));
            quat_alg_conj(&gen, &small);
            ibz_mul(&gen.denom, &gen.denom, &lideal->norm);
            assert(quat_lideal_mul(&I1, lideal, &gen, Bpoo));

            assert(quat_lattice_contains(NULL, &I1.lattice, &mu1));
            quat_alg_conj(&gen, &mu1);
            ibz_mul(&gen.denom, &gen.denom, &I1.norm);
            assert(quat_lideal_mul(&I1, &I1, &gen, Bpoo));

            assert(ibz_cmp(degree1, &I1.norm) == 0);

            // test beta1
            quat_alg_conj(&gen, beta1);
            ibz_mul(&gen.denom, &gen.denom, &lideal->norm);
            assert(quat_lideal_mul(&betatest, lideal, &gen, Bpoo));
            assert(quat_lideal_equals(&betatest, &I1, Bpoo));

            quat_alg_elem_finalize(&gen);
            quat_left_ideal_finalize(&I1);
            quat_left_ideal_finalize(&betatest);
            }
#endif
        }
        {
            // norm d2
            if (!quat_alg_norm(degree2, &d, &mu2, Bpoo) || !ibz_is_one(&d)) {
                ret = ID2ISO_STATUS_FATAL;
                goto cleanup;
            }
            ibz_mul(degree2, degree2, &lideal->norm);
            if (!quat_alg_norm(&n, &d, &small, Bpoo) ||
                !ibz_is_one(&d) || ibz_is_zero(&n)) {
                ret = ID2ISO_STATUS_FATAL;
                goto cleanup;
            }
            ibz_div(degree2, &d, degree2, &n);
            if (!ibz_is_zero(&d)) {
                ret = ID2ISO_STATUS_FATAL;
                goto cleanup;
            }

            if (publish_auxiliary_outputs) {
                // beta2
                quat_alg_mul(beta2, &mu2, &small, Bpoo);
                if (!quat_alg_norm(&n, &d, &small, Bpoo) ||
                    ibz_is_zero(&lideal->norm)) {
                    ret = ID2ISO_STATUS_FATAL;
                    goto cleanup;
                }
                ibz_div(&n, &d, &n, &lideal->norm);
                if (!ibz_is_zero(&d)) {
                    ret = ID2ISO_STATUS_FATAL;
                    goto cleanup;
                }
                ibz_mul(&beta2->denom, &beta2->denom, &n);
                quat_alg_normalize(beta2);
            }
#ifndef NDEBUG
            if (publish_auxiliary_outputs) {
            quat_left_ideal_t I2;
            quat_left_ideal_t betatest;
            quat_alg_elem_t gen;
            quat_left_ideal_init(&I2);
            quat_left_ideal_init(&betatest);
            quat_alg_elem_init(&gen);
            assert(quat_lattice_contains(NULL, &lideal->lattice, &small));
            quat_alg_conj(&gen, &small);
            ibz_mul(&gen.denom, &gen.denom, &lideal->norm);
            assert(quat_lideal_mul(&I2, lideal, &gen, Bpoo));

            assert(quat_lattice_contains(NULL, &I2.lattice, &mu2));
            quat_alg_conj(&gen, &mu2);
            ibz_mul(&gen.denom, &gen.denom, &I2.norm);
            assert(quat_lideal_mul(&I2, &I2, &gen, Bpoo));

            assert(ibz_cmp(degree2, &I2.norm) == 0);

            // test beta1
            quat_alg_conj(&gen, beta2);
            ibz_mul(&gen.denom, &gen.denom, &lideal->norm);
            assert(quat_lideal_mul(&betatest, lideal, &gen, Bpoo));
            assert(quat_lideal_equals(&betatest, &I2, Bpoo));

            quat_alg_elem_finalize(&gen);
            quat_left_ideal_finalize(&I2);
            quat_left_ideal_finalize(&betatest);
            }
#endif
        }
        if (ibz_cmp(degree1, &ibz_const_zero) <= 0 ||
            ibz_cmp(degree2, &ibz_const_zero) <= 0 ||
            !ibz_is_odd(degree1) || !ibz_is_odd(degree2)) {
            ret = ID2ISO_STATUS_FATAL;
            goto cleanup;
        }
#if (ID2ISO_DEBUG_PRINT > 2)
        debug_print("computed odd response degree d1");
#endif

        if (!ec_basis_scalar_mul_ibz(
                &E0_basis, TORSION_EVEN_POWER, &two_c, &BASIS_EVEN, &CURVE_E0)) {
            ret = ID2ISO_STATUS_FATAL;
            goto cleanup;
        }
        copy_basis(&B2, &E0_basis);
        ibz_pow(&two_c, &ibz_const_two, TORSION_EVEN_POWER);
        if (!ibz_invmod(&(tmp), degree1, &two_c)) {
            ret = ID2ISO_STATUS_FATAL;
            goto cleanup;
        }

        /* mu2 is dead after beta2/d2 are derived; reuse its fixed-width
         * storage for the endomorphism scalar instead of another quaternion. */
        quat_alg_elem_set(&mu2, 1, 0, 0, 0, 0);

        ibz_mul(&mu2.coord[0], &theta.coord[0], &(tmp));
        ibz_mul(&mu2.coord[1], &theta.coord[1], &(tmp));
        ibz_mul(&mu2.coord[2], &theta.coord[2], &(tmp));
        ibz_mul(&mu2.coord[3], &theta.coord[3], &(tmp));
        ibz_copy(&mu2.denom, &theta.denom);

        if (!test_basis_order_twof(&E0_basis, &CURVE_E0, TORSION_EVEN_POWER - c) ||
            !endomorphism_application_even_basis(
                 &E0_basis, 0, &CURVE_E0, &mu2, TORSION_EVEN_POWER - c) ||
            !test_basis_order_twof(&E0_basis, &CURVE_E0, TORSION_EVEN_POWER - c)) {
            ret = ID2ISO_STATUS_FATAL;
            goto cleanup;
        }

        // Both are normalized to avoid extra scalar multiplications.
        copy_bases_to_kernel(&ker, &E0_basis, &B2);
        copy_curve(&E0E0.E1, &CURVE_E0);
        copy_curve(&E0E0.E2, &CURVE_E0);

        const quat_alg_elem_t *beta1_for_push = beta1;
        if (!publish_auxiliary_outputs) {
            /* theta is dead once the kernel has been constructed.  Use it as
             * the non-published beta1 value instead of materializing another
             * level-sized quaternion element in the curve-only wrapper. */
            quat_alg_mul(&theta, &mu1, &small, Bpoo);
            if (!quat_alg_norm(&n, &d, &small, Bpoo) ||
                ibz_is_zero(&lideal->norm)) {
                ret = ID2ISO_STATUS_FATAL;
                goto cleanup;
            }
            ibz_div(&n, &d, &n, &lideal->norm);
            if (!ibz_is_zero(&d)) {
                ret = ID2ISO_STATUS_FATAL;
                goto cleanup;
            }
            ibz_mul(&theta.denom, &theta.denom, &n);
            quat_alg_normalize(&theta);
            beta1_for_push = &theta;
        }

        /* B2 is dead after constructing ker; reuse it for the pushed basis. */
        copy_basis(&B2, &BASIS_EVEN);
#ifndef NDEBUG
        assert(weil_basis(&r1, TORSION_EVEN_POWER, &B2, &CURVE_E0));
#endif
        if (!test_basis_order_twof(&BASIS_EVEN, &CURVE_E0, TORSION_EVEN_POWER)) {
            ret = ID2ISO_STATUS_FATAL;
            goto cleanup;
        }
        // compute to be pushed
        {
#if (ID2ISO_DEBUG_PRINT > 2)
            quat_alg_elem_print(beta1_for_push);
#endif
            if (!quat_alg_norm(&n, &d, beta1_for_push, Bpoo) || !ibz_is_one(&d)) {
                ret = ID2ISO_STATUS_FATAL;
                goto cleanup;
            }
            ibz_mul(&d, &lideal->norm, degree1);
            if (ibz_cmp(&d, &n) != 0) {
                ret = ID2ISO_STATUS_FATAL;
                goto cleanup;
            }
#ifndef NDEBUG
            assert(quat_alg_norm(&n, &d, beta1_for_push, Bpoo));
            assert(ibz_is_one(&d));
            assert(ibz_is_odd(&n));
#endif
            assert(test_basis_order_twof(&B2, &CURVE_E0, TORSION_EVEN_POWER));

            // Apply elem * d1^-1

            // scalar mul by d1 mod 2^Torsion

            /* two_c and tmp still hold 2^T and degree1^-1 mod 2^T from the
             * kernel construction above; neither has been modified since. */
            assert(ibz_bitsize(&two_c) == TORSION_EVEN_POWER + 1);
            ibz_pow(&two_c, &ibz_const_two, c);
            ibz_copy(&d, &(tmp));

            quat_alg_elem_set(&mu2, 1, 0, 0, 0, 0);
            ibz_mul(&mu2.coord[0], &beta1_for_push->coord[0], &(tmp));
            ibz_mul(&mu2.coord[1], &beta1_for_push->coord[1], &(tmp));
            ibz_mul(&mu2.coord[2], &beta1_for_push->coord[2], &(tmp));
            ibz_mul(&mu2.coord[3], &beta1_for_push->coord[3], &(tmp));
            ibz_copy(&mu2.denom, &beta1_for_push->denom);

            if (!endomorphism_application_even_basis(
                    &B2, 0, &CURVE_E0, &mu2, TORSION_EVEN_POWER) ||
                !test_basis_order_twof(&B2, &CURVE_E0, TORSION_EVEN_POWER)) {
                ret = ID2ISO_STATUS_FATAL;
                goto cleanup;
            }
        }
        if (!weil_basis(&r1, TORSION_EVEN_POWER, &B2, &CURVE_E0)) {
            ret = ID2ISO_STATUS_FATAL;
            goto cleanup;
        }
        theta_couple_point_t push[3];
        copy_point(&push[0].P1, &B2.P);
        copy_point(&push[1].P1, &B2.Q);
        copy_point(&push[2].P1, &B2.PmQ);
        ec_point_init(&push[0].P2);
        ec_point_init(&push[1].P2);
        ec_point_init(&push[2].P2);

        ret = theta_chain_compute_and_eval_randomized(
            used_torsion, &E0E0, &ker, false, &theta_codomain, push, sizeof(push) / sizeof(*push));
        if (!ret) {
#if (ID2ISO_DEBUG_PRINT > 1)
            debug_print("randomized theta chain failed");
#endif
            goto cleanup;
        }

        // sometimes it is E2 not E1
        copy_point(&basis->P, &push[0].P1);
        copy_point(&basis->Q, &push[1].P1);
        copy_point(&basis->PmQ, &push[2].P1);
        copy_curve(codomain, &theta_codomain.E1);
        memset(array, 0, NWORDS_ORDER * sizeof(digit_t));
        if (!ibz_to_mp_digits_checked(array, NWORDS_ORDER, degree1)) {
            id2iso_wipe_digits(array, NWORDS_ORDER);
            ret = ID2ISO_STATUS_FATAL;
            goto cleanup;
        }
        fp2_pow_vartime(&prod, &r1, &array[0], NWORDS_ORDER);
        id2iso_wipe_digits(array, NWORDS_ORDER);
        if (!weil_basis(&r2, TORSION_EVEN_POWER, basis, codomain)) {
            ret = ID2ISO_STATUS_FATAL;
            goto cleanup;
        }
        if (!fp2_is_equal(&prod, &r2)) {
            copy_point(&basis->P, &push[0].P2);
            copy_point(&basis->Q, &push[1].P2);
            copy_point(&basis->PmQ, &push[2].P2);
            copy_curve(codomain, &theta_codomain.E2);
            if (!weil_basis(&r2, TORSION_EVEN_POWER, basis, codomain) ||
                !fp2_is_equal(&r2, &prod)) {
                ret = ID2ISO_STATUS_FATAL;
                goto cleanup;
            }
#ifndef NDEBUG
#if (ID2ISO_DEBUG_PRINT > 1)
            debug_print("codomain pairing did not match d1");
#endif
            assert(fp2_is_equal(&r2, &prod));
#if (ID2ISO_DEBUG_PRINT > 1)
            debug_print("codomain pairing matched d2");
#endif
#endif
        }
#ifndef NDEBUG
        if (ibz_is_odd(&lideal->norm)) {
            assert(test_point_order_twof(&basis->P, codomain, TORSION_EVEN_POWER));
            assert(test_point_order_twof(&basis->Q, codomain, TORSION_EVEN_POWER));
            assert(test_point_order_twof(&basis->PmQ, codomain, TORSION_EVEN_POWER));
            assert(test_basis_order_twof(basis, codomain, TORSION_EVEN_POWER));
        } else {
            debug_print("checking an even-order ideal");

            ibz_add(&d, degree1, degree2);
            ibz_pow(&n, &ibz_const_two, used_torsion);
            assert(0 == ibz_cmp(&n, &d));
        }
#endif
    }

cleanup:
    if (!publish_auxiliary_outputs) {
#ifndef NDEBUG
        ibz_finalize(&internal_d2);
#endif
        ibz_finalize(&internal_d1);
    }
    ibz_finalize(&n);
    ibz_finalize(&d);
    ibz_finalize(&two_c);
    quat_alg_elem_finalize(&theta);
    quat_alg_elem_finalize(&mu1);
    quat_alg_elem_finalize(&mu2);
    quat_alg_elem_finalize(&small);
    ibz_finalize(&tmp);
    return ret;
}

int
dim2id2iso_ideal_to_isogeny_clapotis(quat_alg_elem_t *beta1,
                                     quat_alg_elem_t *beta2,
                                     ibz_t *u,
                                     ibz_t *v,
                                     ibz_t *d1,
                                     ibz_t *d2,
                                     ec_curve_t *codomain,
                                     ec_basis_t *basis,
                                     const quat_left_ideal_t *lideal,
                                     const quat_alg_t *Bpoo)
{
    return dim2id2iso_ideal_to_isogeny_clapotis_core(beta1,
                                                     beta2,
                                                     u,
                                                     v,
                                                     d1,
                                                     d2,
                                                     codomain,
                                                     basis,
                                                     lideal,
                                                     Bpoo,
                                                     true);
}

int
dim2id2iso_arbitrary_isogeny_evaluation(ec_basis_t *basis, ec_curve_t *codomain, const quat_left_ideal_t *lideal)
{
    return dim2id2iso_ideal_to_isogeny_clapotis_core(NULL,
                                                     NULL,
                                                     NULL,
                                                     NULL,
                                                     NULL,
                                                     NULL,
                                                     codomain,
                                                     basis,
                                                     lideal,
                                                     &QUATALG_PINFTY,
                                                     false);
}
