#!/usr/bin/env python3
"""Validate a curated export and stage pqm4 compile configuration.

This is the import-side counterpart of ``curate_pqm4_library.py``.  It treats
the manifest as a closed, content-addressed source snapshot: every declared
file is hashed while being copied and any undeclared file is rejected.  It
also turns the manifest's curated definitions, options, and include
directories into target-specific pqm4 make rules.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path, PurePosixPath
import re
import shutil
import sys

from curate_pqm4_library import PQM4_COMPILE_OPTION_ALLOWLIST, SCHEMA_VERSION


MANIFEST_KIND = "sqisign-pqm4-library-source-manifest"
CONFIG_BEGIN = "# BEGIN SQISIGN CURATED BACKEND COMPILE FLAGS"
CONFIG_END = "# END SQISIGN CURATED BACKEND COMPILE FLAGS"
HASH_RE = re.compile(r"^[0-9a-f]{64}$")
SAFE_PATH_RE = re.compile(r"^[A-Za-z0-9_./+@%=-]+$")
DEFINITION_RE = re.compile(
    r"^[A-Za-z_][A-Za-z0-9_]*(?:=[A-Za-z0-9_./+,:@%-]+)?$"
)
MAKE_OPTION_RE = re.compile(r"^-[A-Za-z0-9][A-Za-z0-9_=+.,:-]*$")
IMPL_RE = re.compile(
    r"(?m)^([A-Za-z_][A-Za-z0-9_]*)_IMPL[ \t]*:=[ \t]*([^#\s]+)[ \t]*$"
)


class ConsumeError(RuntimeError):
    pass


def safe_relative(value: object, field: str) -> str:
    if not isinstance(value, str) or not value:
        raise ConsumeError(f"{field} must be a non-empty POSIX relative path")
    if "\\" in value:
        raise ConsumeError(f"{field} contains a backslash: {value!r}")
    if not SAFE_PATH_RE.fullmatch(value):
        raise ConsumeError(f"{field} contains an unsafe path character: {value!r}")
    raw_parts = value.split("/")
    if any(part in {"", ".", ".."} for part in raw_parts):
        raise ConsumeError(f"unsafe {field}: {value!r}")
    path = PurePosixPath(value)
    if path.is_absolute():
        raise ConsumeError(f"unsafe {field}: {value!r}")
    return path.as_posix()


def read_record(record: object, category: str) -> tuple[str, int, str]:
    if not isinstance(record, dict):
        raise ConsumeError(f"{category} entry is not an object")
    relative = safe_relative(record.get("path"), f"{category}.path")
    size = record.get("bytes")
    digest = record.get("sha256")
    if not isinstance(size, int) or isinstance(size, bool) or size < 0:
        raise ConsumeError(f"invalid byte count for {relative}")
    if not isinstance(digest, str) or not HASH_RE.fullmatch(digest):
        raise ConsumeError(f"invalid SHA-256 for {relative}")
    return relative, size, digest


def checked_string_list(manifest: dict[str, object], field: str) -> list[str]:
    values = manifest.get(field)
    if not isinstance(values, list) or not all(isinstance(value, str) for value in values):
        raise ConsumeError(f"manifest {field} must be a string list")
    if values != sorted(set(values)):
        raise ConsumeError(f"manifest {field} must be sorted and duplicate-free")
    return values


def digest_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def make_variable_stem(implementation: str) -> str:
    return "SQIQL_IMPORTED_" + re.sub(r"[^A-Za-z0-9]", "_", implementation).upper()


def make_words(values: list[str]) -> str:
    if any(any(character.isspace() for character in value) for value in values):
        raise ConsumeError("manifest make values may not contain whitespace")
    return " ".join(values)


def render_makefile(
    manifest: dict[str, object],
    manifest_digest: str,
    implementation: str,
    definitions: list[str],
    options: list[str],
    include_directories: list[str],
) -> str:
    level = manifest["level"]
    stem = make_variable_stem(implementation)
    target_definitions = [f"-D{definition}" for definition in definitions]
    host_definitions = [
        f"-D{definition}"
        for definition in definitions
        if not definition.startswith("TARGET_")
        and not definition.startswith("SQISIGN_TARGET_OS_")
    ]
    lines = [
        "# Generated by consume_pqm4_manifest.py; do not edit.",
        f"# library-manifest.json sha256={manifest_digest}; level={level}",
        f"{stem}_ROOT := $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))/backend",
        f"{stem}_DEFINITIONS := {make_words(target_definitions)}",
        f"{stem}_HOST_DEFINITIONS := {make_words(host_definitions)}",
        f"{stem}_OPTIONS := {make_words(options)}",
        f"{stem}_INCLUDE_DIRS := $(addprefix $({stem}_ROOT)/,{make_words(include_directories)})",
        # pqm4 adds -Icommon and -Imupq/common before implementation-specific
        # flags.  Use the quote-only search class so a backend's quoted header
        # (notably fips202.h) wins over an unrelated pqm4 header regardless of
        # command-line ordering, without shadowing angle-bracket platform APIs.
        f"{stem}_INCLUDE_FLAGS := $(addprefix -iquote,$({stem}_INCLUDE_DIRS))",
        f"{stem}_CPPFLAGS := $({stem}_DEFINITIONS) $({stem}_INCLUDE_FLAGS)",
        f"{stem}_HOST_CPPFLAGS := $({stem}_HOST_DEFINITIONS) $({stem}_INCLUDE_FLAGS)",
        "",
        f"obj/lib{implementation}.a: CPPFLAGS += $({stem}_CPPFLAGS)",
        f"obj/lib{implementation}.a: CFLAGS += $({stem}_CPPFLAGS) $({stem}_OPTIONS)",
        f"elf/{implementation}_%.elf: CPPFLAGS += $({stem}_CPPFLAGS)",
        f"elf/{implementation}_%.elf: CFLAGS += $({stem}_CPPFLAGS) $({stem}_OPTIONS)",
    ]
    if implementation.startswith("mupq_") and implementation.endswith("_ref"):
        audit = f"obj-host/lib{implementation}_vla_audit.a"
        host_binary = f"bin-host/{implementation}_testvectors"
        lines.extend(
            [
                f"{audit}: HOST_CPPFLAGS += $({stem}_HOST_CPPFLAGS)",
                f"{audit}: HOST_CFLAGS += $({stem}_HOST_CPPFLAGS) $({stem}_OPTIONS)",
                f"{host_binary}: HOST_CPPFLAGS += $({stem}_HOST_CPPFLAGS)",
                f"{host_binary}: HOST_CFLAGS += $({stem}_HOST_CPPFLAGS) $({stem}_OPTIONS)",
                # The fixed-precision DPE layer calls round/llround. pqm4's
                # firmware flags already link libm, but its host harness does
                # not, so keep this dependency scoped to the imported binary.
                f"{host_binary}: HOST_LDLIBS += -lm",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def consume(export_root: Path, implementation_root: Path, stage: Path) -> None:
    manifest_path = export_root / "library-manifest.json"
    source_root = export_root / "source"
    config_path = implementation_root / "config.mk"
    if not manifest_path.is_file() or not source_root.is_dir():
        raise ConsumeError(
            "curated export requires library-manifest.json and source/ at its root"
        )
    if not config_path.is_file():
        raise ConsumeError(f"implementation config is missing: {config_path}")
    if any(stage.iterdir()):
        raise ConsumeError(f"staging directory must be empty: {stage}")

    manifest_bytes = manifest_path.read_bytes()
    try:
        manifest = json.loads(manifest_bytes)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ConsumeError(f"invalid manifest JSON: {manifest_path}") from exc
    if not isinstance(manifest, dict):
        raise ConsumeError("manifest root must be an object")
    if manifest.get("schema_version") != SCHEMA_VERSION:
        raise ConsumeError(
            f"unsupported manifest schema {manifest.get('schema_version')!r}; "
            f"expected {SCHEMA_VERSION}"
        )
    if manifest.get("kind") != MANIFEST_KIND:
        raise ConsumeError(f"unexpected manifest kind: {manifest.get('kind')!r}")
    level = manifest.get("level")
    if level not in (1, 3, 5):
        raise ConsumeError(f"invalid manifest level: {level!r}")

    implementation_match = re.search(r"sqisign-qlapoti-lvl([135])", implementation_root.as_posix())
    if implementation_match and int(implementation_match.group(1)) != level:
        raise ConsumeError(
            f"Level-{level} manifest cannot be injected into {implementation_root}"
        )

    records: dict[str, tuple[int, str]] = {}
    for category in ("translation_units", "headers"):
        entries = manifest.get(category)
        if not isinstance(entries, list) or not entries:
            raise ConsumeError(f"manifest {category} must be a non-empty list")
        for entry in entries:
            relative, size, digest = read_record(entry, category)
            if relative in records:
                raise ConsumeError(f"duplicate manifested path: {relative}")
            records[relative] = (size, digest)

    actual_files: set[str] = set()
    for candidate in source_root.rglob("*"):
        if candidate.is_symlink():
            raise ConsumeError(f"curated source contains a symlink: {candidate}")
        if candidate.is_file():
            actual_files.add(candidate.relative_to(source_root).as_posix())
    expected_files = set(records)
    if actual_files != expected_files:
        missing = sorted(expected_files - actual_files)
        extra = sorted(actual_files - expected_files)
        raise ConsumeError(
            f"curated source file set differs from manifest; missing={missing}, extra={extra}"
        )

    definitions = checked_string_list(manifest, "pqm4_compile_definitions")
    for definition in definitions:
        if not DEFINITION_RE.fullmatch(definition):
            raise ConsumeError(f"unsafe compile definition: {definition!r}")
    options = checked_string_list(manifest, "pqm4_compile_options")
    for option in options:
        if option not in PQM4_COMPILE_OPTION_ALLOWLIST or not MAKE_OPTION_RE.fullmatch(option):
            raise ConsumeError(f"unsafe or unapproved compile option: {option!r}")
    include_directories = checked_string_list(
        manifest, "pqm4_compile_include_directories"
    )
    include_directories = [
        safe_relative(value, "pqm4_compile_include_directories")
        for value in include_directories
    ]
    for relative in include_directories:
        if not (source_root / relative).is_dir():
            raise ConsumeError(f"manifested include directory is absent: {relative}")

    config_bytes = config_path.read_bytes()
    try:
        config_text = config_bytes.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ConsumeError(f"config.mk is not UTF-8: {config_path}") from exc
    if CONFIG_BEGIN in config_text or "backend_compile_flags.mk" in config_text:
        raise ConsumeError("config.mk already contains backend manifest integration")
    implementation_matches = IMPL_RE.findall(config_text)
    if len(implementation_matches) != 1:
        raise ConsumeError(
            "config.mk must define exactly one <PREFIX>_IMPL := implementation variable"
        )
    _, implementation = implementation_matches[0]
    expected_level = re.search(r"sqisign-qlapoti-lvl([135])", implementation)
    if not expected_level or int(expected_level.group(1)) != level:
        raise ConsumeError(
            f"manifest level {level} does not match config implementation {implementation}"
        )

    backend_stage = stage / "backend"
    for relative in sorted(records):
        size, expected_digest = records[relative]
        content = (source_root / relative).read_bytes()
        if len(content) != size or digest_bytes(content) != expected_digest:
            raise ConsumeError(f"source changed or is corrupt: {relative}")
        destination = backend_stage / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(content)
        if digest_bytes(destination.read_bytes()) != expected_digest:
            raise ConsumeError(f"staged copy hash mismatch: {relative}")

    manifest_digest = digest_bytes(manifest_bytes)
    (stage / "BACKEND_LIBRARY_MANIFEST.json").write_bytes(manifest_bytes)
    (stage / "backend_compile_flags.mk").write_text(
        render_makefile(
            manifest,
            manifest_digest,
            implementation,
            definitions,
            options,
            include_directories,
        ),
        encoding="utf-8",
        newline="\n",
    )
    if config_text and not config_text.endswith("\n"):
        config_text += "\n"
    patched_config = (
        config_text
        + "\n"
        + CONFIG_BEGIN
        + " (generated by inject_backend.sh)\n"
        + "include $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))/backend_compile_flags.mk\n"
        + CONFIG_END
        + "\n"
    )
    (stage / "config.mk").write_text(
        patched_config, encoding="utf-8", newline="\n"
    )
    shutil.copymode(config_path, stage / "config.mk")
    (stage / "BACKEND_CONFIG_ORIGINAL.sha256").write_text(
        digest_bytes(config_bytes) + "\n", encoding="ascii"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--export-root", type=Path, required=True)
    parser.add_argument("--implementation", type=Path, required=True)
    parser.add_argument("--stage", type=Path, required=True)
    args = parser.parse_args()
    consume(
        args.export_root.resolve(),
        args.implementation.resolve(),
        args.stage.resolve(),
    )
    print("CURATED PQM4 MANIFEST CONSUMPTION: PASS")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ConsumeError as error:
        raise SystemExit(f"CURATED PQM4 MANIFEST CONSUMPTION: FAIL\n{error}")
