#!/usr/bin/env python3
"""Render the deterministic wrapper translation units used by pqm4 imports.

This module is the Python form of the wrapper-generation step in
``scripts/inject_backend.sh``.  Keeping the renderer callable lets provenance
audits rebuild the expected injected payload without modifying the pqm4 tree.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import stat


SOURCE_SUFFIXES = {".c", ".s", ".S"}
PLAIN_ASSEMBLY_INCLUDE_RE = re.compile(
    r"^\s*(?:\.include|#\s*include)\b", re.MULTILINE
)


class WrapperRenderError(RuntimeError):
    pass


def _require_regular_backend(backend: Path) -> list[Path]:
    if backend.is_symlink() or not backend.is_dir():
        raise WrapperRenderError(f"backend is not a regular directory: {backend}")

    sources: list[Path] = []
    for candidate in backend.rglob("*"):
        mode = candidate.lstat().st_mode
        relative = candidate.relative_to(backend).as_posix()
        if stat.S_ISLNK(mode):
            raise WrapperRenderError(f"backend contains a symlink: {relative}")
        if stat.S_ISDIR(mode):
            continue
        if not stat.S_ISREG(mode):
            raise WrapperRenderError(
                f"backend contains a special filesystem entry: {relative}"
            )
        if candidate.suffix in SOURCE_SUFFIXES:
            sources.append(candidate)
    return sorted(sources, key=lambda path: path.relative_to(backend).as_posix())


def render_backend_wrappers(backend: Path, destination: Path) -> list[tuple[str, str]]:
    """Create wrappers and ``BACKEND_TRANSLATION_UNITS.txt`` in *destination*.

    The returned pairs are ``(wrapper name, backend-relative source)`` in the
    exact deterministic order used for wrapper numbering.
    """

    if backend.is_symlink() or not backend.is_dir():
        raise WrapperRenderError(f"backend is not a regular directory: {backend}")
    if destination.is_symlink() or not destination.is_dir():
        raise WrapperRenderError(
            f"wrapper destination is not a regular directory: {destination}"
        )
    backend = backend.resolve()
    destination = destination.resolve()
    existing = sorted(destination.glob("backend_tu_*"))
    translation_units = destination / "BACKEND_TRANSLATION_UNITS.txt"
    if existing or translation_units.exists() or translation_units.is_symlink():
        names = [path.name for path in existing]
        if translation_units.exists() or translation_units.is_symlink():
            names.append(translation_units.name)
        raise WrapperRenderError(
            "refusing existing generated wrapper artifacts: " + ", ".join(names)
        )

    units: list[tuple[str, str]] = []
    for index, source in enumerate(_require_regular_backend(backend), 1):
        relative = source.relative_to(backend).as_posix()
        suffix = source.suffix
        wrapper = destination / f"backend_tu_{index:04d}{suffix}"
        if suffix == ".c":
            wrapper.write_text(
                "/* generated by inject_backend.sh; do not edit */\n"
                "#if defined(__GNUC__)\n"
                "#pragma GCC diagnostic error \"-Wvla\"\n"
                "#endif\n"
                f'#line 1 "backend/{relative}"\n'
                f'#include "backend/{relative}"\n',
                encoding="utf-8",
                newline="\n",
            )
        elif suffix == ".S":
            wrapper.write_text(
                "/* generated by inject_backend.sh; do not edit */\n"
                f'#include "backend/{relative}"\n',
                encoding="utf-8",
                newline="\n",
            )
        else:
            text = source.read_text(encoding="utf-8", errors="replace")
            if PLAIN_ASSEMBLY_INCLUDE_RE.search(text):
                raise WrapperRenderError(
                    "plain .s file has relative includes; convert to .S or "
                    f"flatten manually: {relative}"
                )
            wrapper.write_bytes(source.read_bytes())
        units.append((wrapper.name, relative))

    if not units:
        raise WrapperRenderError("no C/assembly translation units found in backend source")
    translation_units.write_text(
        "".join(
            f"{wrapper} includes backend/{relative}\n"
            for wrapper, relative in units
        ),
        encoding="utf-8",
        newline="\n",
    )
    return units


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--backend", type=Path, required=True)
    parser.add_argument("--destination", type=Path, required=True)
    args = parser.parse_args()
    units = render_backend_wrappers(args.backend, args.destination)
    print(f"Created {len(units)} pqm4-visible wrapper translation units")
    return 0


__all__ = ["WrapperRenderError", "render_backend_wrappers"]


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except WrapperRenderError as error:
        raise SystemExit(f"PQM4 BACKEND WRAPPER RENDER: FAIL\n{error}")
